name: React app deployement

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      
      - name: Restore CI Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-16-${{ hashFiles('**/bun.lockb') }}

      - name: Install Dependencies
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: bun install --frozen-lockfile --silent

      - name: Build and deploy
        run: |
          bun run build
          echo "matikkaeditori.fi" >> dist/CNAME
          echo "VERSION: " >> dist/VERSION
          echo $(git rev-parse --short "$GITHUB_SHA") >> dist/VERSION
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree dist add --all
          git commit -m "Automatic React build & deploy"
          git push origin HEAD:gh-pages --force
